[project]
name = "smart-binary-options-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryptography>=46.0.3",
    "requests>=2.32.5",
]
